[package]
name = "random_rpg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.13"
noise = { version = "0.9.0", features = ["images"] }
rand = "0.8.5"
rand_distr = "0.4.3"
serde = { version = "1.0.204", features = ["derive"] }
serde_yaml = "0.9.34"
