size:
  x: 1024
  y: 512
layers:
- id: fb0
  layer_type: !SimpleLayer
    seed: null
    octaves: 6
    lacunarity: 2.0943951023931953
    persistence: 0.5
    frequency: 2.0
- id: cu
  layer_type: !TerrainShape
    input: fb0
    control_points:
    - x: -2.0
      y: -2.0
    - x: -1.0
      y: -1.0
    - x: 1.0
      y: 1.0
    - x: 2.0
      y: 2.0
- id: fb1
  layer_type: !SimpleLayer
    seed: null
    octaves: 6
    lacunarity: 2.0943951023931953
    persistence: 0.5
    frequency: 2.0
- id: sb
  layer_type: !ScaleBias
    input: fb1
    scale: 0.375
    bias: 0.625
- id: mi
  layer_type: !Min
    lhs: sb
    rhs: cu
- id: cl
  layer_type: !Clamp
    input: mi
    lower_bounds: -1.0
    upper_bounds: 1.0
color_gradient:
- position: -1.0
  color:
    r: 0
    g: 0
    b: 0
- position: -0.015625
  color:
    r: 6
    g: 58
    b: 127
- position: -0.00006103515625
  color:
    r: 14
    g: 112
    b: 192
- position: 0.0
  color:
    r: 70
    g: 120
    b: 60
- position: 0.0625
  color:
    r: 110
    g: 140
    b: 75
- position: 0.125
  color:
    r: 160
    g: 140
    b: 111
- position: 0.1875
  color:
    r: 184
    g: 163
    b: 141
- position: 0.25
  color:
    r: 128
    g: 128
    b: 128
- position: 0.34375
  color:
    r: 128
    g: 128
    b: 128
- position: 0.375
  color:
    r: 250
    g: 250
    b: 250
- position: 1.0
  color:
    r: 255
    g: 255
    b: 255
